apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-eta-deploy
  labels:
    app: health-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-eta-app
  template:
    metadata:
      labels:
        app: health-eta-app
    spec:
      containers:
      - name: health-eta-container
        image: vinisasthi/demo-pro-health
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: health-eta-np-service
  labels:
    app: health-eta-app
spec:
  selector:
    app: health-eta-app

  type: NodePort
  ports:
  - nodePort: 31033    
    port: 8083
    targetPort: 8083
